In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 


train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [3]:
model = nn.Linear(2, 2, bias=False)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [4]:
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.0738, 0.5151],
        [0.7476, 0.4850]], requires_grad=True)], Cost : 0.175
Epoch : 2000, Model : [Parameter containing:
tensor([[0.4076, 0.2453],
        [0.8199, 0.4265]], requires_grad=True)], Cost : 0.111
Epoch : 3000, Model : [Parameter containing:
tensor([[0.6729, 0.0307],
        [0.8774, 0.3800]], requires_grad=True)], Cost : 0.071
Epoch : 4000, Model : [Parameter containing:
tensor([[ 0.8836, -0.1399],
        [ 0.9231,  0.3430]], requires_grad=True)], Cost : 0.045
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.0512, -0.2753],
        [ 0.9594,  0.3137]], requires_grad=True)], Cost : 0.028
Epoch : 6000, Model : [Parameter containing:
tensor([[ 1.1843, -0.3831],
        [ 0.9883,  0.2904]], requires_grad=True)], Cost : 0.018
Epoch : 7000, Model : [Parameter containing:
tensor([[ 1.2902, -0.4686],
        [ 1.0112,  0.2718]], requires_grad=True)], Cost : 0.011
Epoch : 8000, Model : [Parameter containing:
tensor([