In [1]:
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 


train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [2]:
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [3]:
model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [4]:
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.2231, 0.4622],
        [0.2325, 0.9854]], requires_grad=True), Parameter containing:
tensor([-0.3576, -0.4395], requires_grad=True)], Cost : 0.092
Epoch : 2000, Model : [Parameter containing:
tensor([[0.4411, 0.3493],
        [0.3158, 0.9423]], requires_grad=True), Parameter containing:
tensor([-0.6885, -0.5661], requires_grad=True)], Cost : 0.024
Epoch : 3000, Model : [Parameter containing:
tensor([[0.5523, 0.2919],
        [0.3583, 0.9203]], requires_grad=True), Parameter containing:
tensor([-0.8571, -0.6305], requires_grad=True)], Cost : 0.006
Epoch : 4000, Model : [Parameter containing:
tensor([[0.6090, 0.2627],
        [0.3800, 0.9091]], requires_grad=True), Parameter containing:
tensor([-0.9430, -0.6634], requires_grad=True)], Cost : 0.002
Epoch : 5000, Model : [Parameter containing:
tensor([[0.6378, 0.2477],
        [0.3910, 0.9034]], requires_grad=True), Parameter containing:
tensor([-0.9868, -0.6801], requires_grad=True)]